// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module KalmanFilterKernel_matMultiply_float_6_6_6_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_in_L_address0,
        mat_in_L_ce0,
        mat_in_L_q0,
        mat_in_R_0_read,
        mat_in_R_1_read,
        mat_in_R_2_read,
        mat_out_address0,
        mat_out_ce0,
        mat_out_we0,
        mat_out_d0
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] mat_in_L_address0;
output   mat_in_L_ce0;
input  [31:0] mat_in_L_q0;
input  [31:0] mat_in_R_0_read;
input  [31:0] mat_in_R_1_read;
input  [31:0] mat_in_R_2_read;
output  [5:0] mat_out_address0;
output   mat_out_ce0;
output   mat_out_we0;
output  [31:0] mat_out_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mat_in_L_ce0;
reg mat_out_ce0;
reg mat_out_we0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] add_ln13_fu_150_p2;
reg   [2:0] add_ln13_reg_257;
wire    ap_CS_fsm_state2;
wire   [4:0] empty_fu_174_p2;
reg   [4:0] empty_reg_265;
wire   [0:0] icmp_ln13_fu_160_p2;
reg   [5:0] mat_out_addr_reg_270;
wire    ap_CS_fsm_state3;
wire   [0:0] ap_phi_mux_k_phi_fu_114_p4;
wire   [1:0] add_ln23_fu_195_p2;
reg   [1:0] add_ln23_reg_275;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln23_fu_205_p2;
wire   [31:0] tmp_fu_221_p5;
reg   [31:0] tmp_reg_288;
wire   [0:0] icmp_ln27_fu_230_p2;
reg   [0:0] icmp_ln27_reg_293;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_145_p2;
reg   [31:0] mul_reg_303;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_fu_236_p3;
wire    ap_CS_fsm_state11;
reg   [2:0] i_reg_97;
reg   [0:0] k_reg_109;
reg   [1:0] j_reg_122;
reg   [31:0] add1913_reg_133;
wire   [63:0] zext_ln20_fu_190_p1;
wire   [63:0] zext_ln27_fu_216_p1;
wire   [4:0] p_shl_fu_166_p3;
wire   [4:0] zext_ln13_fu_156_p1;
wire   [2:0] zext_ln17_fu_180_p1;
wire   [2:0] add_ln20_fu_184_p2;
wire   [4:0] zext_ln23_fu_201_p1;
wire   [4:0] add_ln27_fu_211_p2;
wire    ap_CS_fsm_state9;
reg    grp_fu_236_in_valid;
reg   [10:0] ap_NS_fsm;
wire   [31:0] grp_fu_236_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

KalmanFilterKernel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mat_in_L_q0),
    .din1(tmp_reg_288),
    .ce(1'b1),
    .dout(grp_fu_145_p2)
);

KalmanFilterKernel_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U9(
    .din0(mat_in_R_0_read),
    .din1(mat_in_R_1_read),
    .din2(mat_in_R_2_read),
    .din3(j_reg_122),
    .dout(tmp_fu_221_p5)
);

KalmanFilterKernel_facc_32ns_32ns_1ns_32_3_no_dsp_1 #(
    .DWIDTH( 32 ))
facc_32ns_32ns_1ns_32_3_no_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .ce(1'b1),
    .in_data(mul_reg_303),
    .in_last(icmp_ln27_reg_293),
    .in_valid(grp_fu_236_in_valid),
    .out_data(grp_fu_236_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_k_phi_fu_114_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        add1913_reg_133 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        add1913_reg_133 <= grp_fu_236_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_97 <= 3'd0;
    end else if (((ap_phi_mux_k_phi_fu_114_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_97 <= add_ln13_reg_257;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_k_phi_fu_114_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_reg_122 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        j_reg_122 <= add_ln23_reg_275;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_160_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        k_reg_109 <= 1'd0;
    end else if (((icmp_ln23_fu_205_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        k_reg_109 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln13_reg_257 <= add_ln13_fu_150_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln23_reg_275 <= add_ln23_fu_195_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_160_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_265 <= empty_fu_174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_fu_205_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        icmp_ln27_reg_293 <= icmp_ln27_fu_230_p2;
        tmp_reg_288 <= tmp_fu_221_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_k_phi_fu_114_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mat_out_addr_reg_270[2 : 0] <= zext_ln20_fu_190_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_reg_303 <= grp_fu_145_p2;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((icmp_ln13_fu_160_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_fu_160_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_236_in_valid = 1'b1;
    end else begin
        grp_fu_236_in_valid = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_in_L_ce0 = 1'b1;
    end else begin
        mat_in_L_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_out_ce0 = 1'b1;
    end else begin
        mat_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_fu_205_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        mat_out_we0 = 1'b1;
    end else begin
        mat_out_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln13_fu_160_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((ap_phi_mux_k_phi_fu_114_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln23_fu_205_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_150_p2 = (i_reg_97 + 3'd1);

assign add_ln20_fu_184_p2 = (zext_ln17_fu_180_p1 + i_reg_97);

assign add_ln23_fu_195_p2 = (j_reg_122 + 2'd1);

assign add_ln27_fu_211_p2 = (zext_ln23_fu_201_p1 + empty_reg_265);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_phi_mux_k_phi_fu_114_p4 = k_reg_109;

assign empty_fu_174_p2 = (p_shl_fu_166_p3 - zext_ln13_fu_156_p1);

assign icmp_ln13_fu_160_p2 = ((i_reg_97 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_205_p2 = ((j_reg_122 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_230_p2 = ((add_ln23_fu_195_p2 == 2'd3) ? 1'b1 : 1'b0);

assign mat_in_L_address0 = zext_ln27_fu_216_p1;

assign mat_out_address0 = mat_out_addr_reg_270;

assign mat_out_d0 = add1913_reg_133;

assign p_shl_fu_166_p3 = {{i_reg_97}, {2'd0}};

assign zext_ln13_fu_156_p1 = i_reg_97;

assign zext_ln17_fu_180_p1 = k_reg_109;

assign zext_ln20_fu_190_p1 = add_ln20_fu_184_p2;

assign zext_ln23_fu_201_p1 = j_reg_122;

assign zext_ln27_fu_216_p1 = add_ln27_fu_211_p2;

always @ (posedge ap_clk) begin
    mat_out_addr_reg_270[5:3] <= 3'b000;
end

endmodule //KalmanFilterKernel_matMultiply_float_6_6_6_2
